//! Compile-time schema embedding (design §3).
//!
//! Reads `schemas/registry.json` — the checked-in `$id` -> repo path resolver
//! map — and emits a generated `SCHEMA_TABLE: &[(&str, &str)]` where each schema
//! body is pulled in with `include_str!`. The schema set in `schemas/` stays the
//! single source of truth (ADR-0001 / ADR-0002); nothing is copied and the
//! binary is hermetic at runtime.
//!
//! It also embeds the checked-in known-capability registry
//! `schemas/capabilities.json` (F2-07) into a generated `CAPABILITIES_JSON`
//! constant. Its contents are OPEN under §58 and only the *presence* of a
//! well-formed registry is normative here: capability existence is a lookup, not
//! a schema shape.
//!
//! The build fails, loudly, if:
//!   * `schemas/registry.json` is missing or not valid JSON, or has no `ids`;
//!   * any mapped `$id` points at a file that does not exist on disk;
//!   * `schemas/capabilities.json` is missing, not valid JSON, or has no
//!     `capabilities` array (a missing registry must never mean "all known").
//!
//! Absolute paths are written into `include_str!` because the generated files
//! live in `OUT_DIR`, so a path relative to `src/` would not resolve.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("build.rs: CARGO_MANIFEST_DIR unset"));
    let repo_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("build.rs: packages/validator must live two levels below the repo root")
        .to_path_buf();

    let registry_path = repo_root.join("schemas").join("registry.json");
    println!("cargo:rerun-if-changed={}", registry_path.display());

    let registry_raw = fs::read_to_string(&registry_path)
        .unwrap_or_else(|e| panic!("build.rs: cannot read {}: {e}", registry_path.display()));
    let registry: serde_json::Value = serde_json::from_str(&registry_raw).unwrap_or_else(|e| {
        panic!(
            "build.rs: {} is not valid JSON: {e}",
            registry_path.display()
        )
    });

    let ids = registry
        .get("ids")
        .and_then(serde_json::Value::as_object)
        .unwrap_or_else(|| panic!("build.rs: {} has no `ids` object", registry_path.display()));
    if ids.is_empty() {
        panic!(
            "build.rs: {} maps no $id to a path",
            registry_path.display()
        );
    }

    let mut entries: Vec<(String, PathBuf)> = Vec::with_capacity(ids.len());
    for (id, rel) in ids {
        let rel = rel
            .as_str()
            .unwrap_or_else(|| panic!("build.rs: registry entry `{id}` is not a string path"));
        let abs = repo_root.join(rel);
        if !abs.is_file() {
            panic!(
                "build.rs: registry maps `{id}` -> `{rel}`, but no file exists at {}",
                abs.display()
            );
        }
        println!("cargo:rerun-if-changed={}", abs.display());
        entries.push((id.clone(), abs));
    }
    // Deterministic table order regardless of the JSON object iteration order.
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut generated = String::new();
    generated
        .push_str("// @generated by packages/validator/build.rs from schemas/registry.json.\n");
    generated.push_str("// Do not edit; the schema set in schemas/ is the source of truth.\n");
    generated.push_str("pub static SCHEMA_TABLE: &[(&str, &str)] = &[\n");
    for (id, abs) in &entries {
        let abs = abs.to_string_lossy().replace('\\', "/");
        generated.push_str(&format!("    ({id:?}, include_str!(r#\"{abs}\"#)),\n"));
    }
    generated.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("build.rs: OUT_DIR unset"));
    let dest = out_dir.join("schema_table.rs");
    fs::write(&dest, generated)
        .unwrap_or_else(|e| panic!("build.rs: cannot write {}: {e}", dest.display()));

    // --- Known-capability registry (F2-07) ---------------------------------
    //
    // The registry is embedded read-only. A missing file is a HARD build
    // failure: without a registry the validator cannot resolve capabilities and
    // must never fall back to treating every identifier as known.
    let capabilities_path = repo_root.join("schemas").join("capabilities.json");
    println!("cargo:rerun-if-changed={}", capabilities_path.display());

    let capabilities_raw = fs::read_to_string(&capabilities_path).unwrap_or_else(|e| {
        panic!(
            "build.rs: cannot read the known-capability registry {}: {e} \
             (F2-07: a missing registry is a loud failure, never an implicit \
             \"all known\")",
            capabilities_path.display()
        )
    });
    let capabilities: serde_json::Value =
        serde_json::from_str(&capabilities_raw).unwrap_or_else(|e| {
            panic!(
                "build.rs: {} is not valid JSON: {e}",
                capabilities_path.display()
            )
        });
    if !capabilities
        .get("capabilities")
        .is_some_and(serde_json::Value::is_array)
    {
        panic!(
            "build.rs: {} has no `capabilities` array",
            capabilities_path.display()
        );
    }

    let capabilities_abs = capabilities_path.to_string_lossy().replace('\\', "/");
    let capabilities_generated = format!(
        "// @generated by packages/validator/build.rs from schemas/capabilities.json.\n\
         // Do not edit; the checked-in registry is the source (contents OPEN, §58).\n\
         pub static CAPABILITIES_JSON: &str = include_str!(r#\"{capabilities_abs}\"#);\n"
    );
    let capabilities_dest = out_dir.join("capability_registry.rs");
    fs::write(&capabilities_dest, capabilities_generated).unwrap_or_else(|e| {
        panic!(
            "build.rs: cannot write {}: {e}",
            capabilities_dest.display()
        )
    });
}
